apiVersion: apps/v1
kind: Deployment
metadata: 
  name: base-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: base-app
  template:
    metadata:
      labels:
        app: base-app
    spec:
      containers:
        - name: app-container
          image: nginx/nginx-ingress

---
apiVersion: v1
kind: Service
metadata:
  name: base-app-service
spec:
  selector:
    app: base-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
